# --- Server Port ---
server.port=8084
# --- Datenbank ---
spring.datasource.url=jdbc:mariadb://localhost:3308/users
spring.datasource.username=devuser
spring.datasource.password=devpass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# --- Keycloak Clients (IDs zentral, Secrets lieber aus Env) ---
keycloak.base-url=http://localhost:8079
keycloak.realm=3DPrintVerse
keycloak.admin.client.id=admin-client
keycloak.admin.client.secret=03KcKXff5x7vipclLcDmfFZkafkLXbT1
keycloak.user.client.id=user-client
keycloak.user.client.secret=YbtkUnJn1ioTSglyQGWjOyMkENBwOvJi
# --- Security ---
security.public-endpoints=/api/auth/register,/api/auth/login,/api/auth/activate/**,/api/auth/forgot-password,/api/auth/reset-password,/api/auth/refresh
security.public-endpoints[1]=/api/auth/login
security.public-endpoints[2]=/api/auth/activate/**
security.public-endpoints[3]=/api/auth/forgot-password
security.public-endpoints[4]=/api/auth/reset-password
security.public-endpoints[5]=/api/auth/refresh